exclude_patterns:
  - "**/*.spec.js"
  - "**/vendor/"
  - "**/node_modules/"
  - "**/.github/"
  - ".github/"
  - "public/"
  - "database/"
  - "coverage/"
  - "seeds/"
  - "migrations/"
  - "*.md"
  - "*.json"
