exclude_patterns:
  - "**/*.spec.js"
  - "**/vendor/"
  - "**/node_modules/"
  - "**/.github/"
  - ".github/"
  - "public/"
  - "database/"
  - "coverage/"
  - "seeds/"
  - "migrations/"
  - "*.md"
  - "*.json"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          count_threshold: 5
          mass_threshold: 75
